// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/secrets/secrets.proto

package secrets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Secret) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Secret) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateSecretRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrgId          string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PlaintextValue string                 `protobuf:"bytes,4,opt,name=plaintext_value,json=plaintextValue,proto3" json:"plaintext_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecretRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSecretRequest) GetPlaintextValue() string {
	if x != nil {
		return x.PlaintextValue
	}
	return ""
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{3}
}

func (x *ListSecretsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type UpdateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                               // empty = no change
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                 // empty = no change
	NewValue      *string                `protobuf:"bytes,5,opt,name=new_value,json=newValue,proto3,oneof" json:"new_value,omitempty"` // absent = no change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSecretRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *UpdateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSecretRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSecretRequest) GetNewValue() string {
	if x != nil && x.NewValue != nil {
		return *x.NewValue
	}
	return ""
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{6}
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSecretRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DeleteSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{8}
}

type SecretGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	AllowedHosts  []string               `protobuf:"bytes,5,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGroup) Reset() {
	*x = SecretGroup{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGroup) ProtoMessage() {}

func (x *SecretGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGroup.ProtoReflect.Descriptor instead.
func (*SecretGroup) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{9}
}

func (x *SecretGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretGroup) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SecretGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecretGroup) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

func (x *SecretGroup) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateSecretGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AllowedHosts  []string               `protobuf:"bytes,4,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretGroupRequest) Reset() {
	*x = CreateSecretGroupRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretGroupRequest) ProtoMessage() {}

func (x *CreateSecretGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSecretGroupRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateSecretGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSecretGroupRequest) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

type CreateSecretGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *SecretGroup           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretGroupResponse) Reset() {
	*x = CreateSecretGroupResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretGroupResponse) ProtoMessage() {}

func (x *CreateSecretGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSecretGroupResponse) GetGroup() *SecretGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type ListSecretGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretGroupsRequest) Reset() {
	*x = ListSecretGroupsRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretGroupsRequest) ProtoMessage() {}

func (x *ListSecretGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretGroupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{12}
}

func (x *ListSecretGroupsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type ListSecretGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*SecretGroup         `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretGroupsResponse) Reset() {
	*x = ListSecretGroupsResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretGroupsResponse) ProtoMessage() {}

func (x *ListSecretGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{13}
}

func (x *ListSecretGroupsResponse) GetGroups() []*SecretGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetSecretGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretGroupRequest) Reset() {
	*x = GetSecretGroupRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretGroupRequest) ProtoMessage() {}

func (x *GetSecretGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretGroupRequest.ProtoReflect.Descriptor instead.
func (*GetSecretGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{14}
}

func (x *GetSecretGroupRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GetSecretGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetSecretGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *SecretGroup           `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretGroupResponse) Reset() {
	*x = GetSecretGroupResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretGroupResponse) ProtoMessage() {}

func (x *GetSecretGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretGroupResponse.ProtoReflect.Descriptor instead.
func (*GetSecretGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{15}
}

func (x *GetSecretGroupResponse) GetGroup() *SecretGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type UpdateSecretGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`               // empty = no change
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"` // empty = no change
	AllowedHosts  []string               `protobuf:"bytes,5,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretGroupRequest) Reset() {
	*x = UpdateSecretGroupRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretGroupRequest) ProtoMessage() {}

func (x *UpdateSecretGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateSecretGroupRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UpdateSecretGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UpdateSecretGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSecretGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSecretGroupRequest) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

type UpdateSecretGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretGroupResponse) Reset() {
	*x = UpdateSecretGroupResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretGroupResponse) ProtoMessage() {}

func (x *UpdateSecretGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretGroupResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{17}
}

type DeleteSecretGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretGroupRequest) Reset() {
	*x = DeleteSecretGroupRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretGroupRequest) ProtoMessage() {}

func (x *DeleteSecretGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteSecretGroupRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *DeleteSecretGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type DeleteSecretGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretGroupResponse) Reset() {
	*x = DeleteSecretGroupResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretGroupResponse) ProtoMessage() {}

func (x *DeleteSecretGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{19}
}

type SecretGroupEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SecretId      string                 `protobuf:"bytes,3,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	SecretName    string                 `protobuf:"bytes,4,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"` // populated by joins
	EnvVarName    string                 `protobuf:"bytes,5,opt,name=env_var_name,json=envVarName,proto3" json:"env_var_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGroupEntry) Reset() {
	*x = SecretGroupEntry{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGroupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGroupEntry) ProtoMessage() {}

func (x *SecretGroupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGroupEntry.ProtoReflect.Descriptor instead.
func (*SecretGroupEntry) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{20}
}

func (x *SecretGroupEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretGroupEntry) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SecretGroupEntry) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SecretGroupEntry) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretGroupEntry) GetEnvVarName() string {
	if x != nil {
		return x.EnvVarName
	}
	return ""
}

type SetSecretGroupEntriesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	GroupId       string                   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Entries       []*SecretGroupEntryInput `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretGroupEntriesRequest) Reset() {
	*x = SetSecretGroupEntriesRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretGroupEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretGroupEntriesRequest) ProtoMessage() {}

func (x *SetSecretGroupEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretGroupEntriesRequest.ProtoReflect.Descriptor instead.
func (*SetSecretGroupEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{21}
}

func (x *SetSecretGroupEntriesRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SetSecretGroupEntriesRequest) GetEntries() []*SecretGroupEntryInput {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SecretGroupEntryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	EnvVarName    string                 `protobuf:"bytes,2,opt,name=env_var_name,json=envVarName,proto3" json:"env_var_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGroupEntryInput) Reset() {
	*x = SecretGroupEntryInput{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGroupEntryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGroupEntryInput) ProtoMessage() {}

func (x *SecretGroupEntryInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGroupEntryInput.ProtoReflect.Descriptor instead.
func (*SecretGroupEntryInput) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{22}
}

func (x *SecretGroupEntryInput) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SecretGroupEntryInput) GetEnvVarName() string {
	if x != nil {
		return x.EnvVarName
	}
	return ""
}

type SetSecretGroupEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretGroupEntriesResponse) Reset() {
	*x = SetSecretGroupEntriesResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretGroupEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretGroupEntriesResponse) ProtoMessage() {}

func (x *SetSecretGroupEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretGroupEntriesResponse.ProtoReflect.Descriptor instead.
func (*SetSecretGroupEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{23}
}

type GetSecretGroupEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretGroupEntriesRequest) Reset() {
	*x = GetSecretGroupEntriesRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretGroupEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretGroupEntriesRequest) ProtoMessage() {}

func (x *GetSecretGroupEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretGroupEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetSecretGroupEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{24}
}

func (x *GetSecretGroupEntriesRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GetSecretGroupEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*SecretGroupEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretGroupEntriesResponse) Reset() {
	*x = GetSecretGroupEntriesResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretGroupEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretGroupEntriesResponse) ProtoMessage() {}

func (x *GetSecretGroupEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretGroupEntriesResponse.ProtoReflect.Descriptor instead.
func (*GetSecretGroupEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{25}
}

func (x *GetSecretGroupEntriesResponse) GetEntries() []*SecretGroupEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ResolveSecretGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSecretGroupRequest) Reset() {
	*x = ResolveSecretGroupRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSecretGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSecretGroupRequest) ProtoMessage() {}

func (x *ResolveSecretGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSecretGroupRequest.ProtoReflect.Descriptor instead.
func (*ResolveSecretGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{26}
}

func (x *ResolveSecretGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ResolveSecretGroupRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type ResolveSecretGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvVars       map[string]string      `protobuf:"bytes,1,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AllowedHosts  []string               `protobuf:"bytes,2,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSecretGroupResponse) Reset() {
	*x = ResolveSecretGroupResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSecretGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSecretGroupResponse) ProtoMessage() {}

func (x *ResolveSecretGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSecretGroupResponse.ProtoReflect.Descriptor instead.
func (*ResolveSecretGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{27}
}

func (x *ResolveSecretGroupResponse) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *ResolveSecretGroupResponse) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

type CreateSecretSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SandboxId     string                 `protobuf:"bytes,3,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = default (86400s / 24h)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretSessionRequest) Reset() {
	*x = CreateSecretSessionRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretSessionRequest) ProtoMessage() {}

func (x *CreateSecretSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{28}
}

func (x *CreateSecretSessionRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateSecretSessionRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateSecretSessionRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSecretSessionRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type CreateSecretSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`                                                                           // opaque bearer token for ResolveSecretSession
	SealedTokens  map[string]string      `protobuf:"bytes,3,rep,name=sealed_tokens,json=sealedTokens,proto3" json:"sealed_tokens,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // {envVarName: "osb_sealed_xxx"}
	AllowedHosts  []string               `protobuf:"bytes,4,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // unix seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretSessionResponse) Reset() {
	*x = CreateSecretSessionResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretSessionResponse) ProtoMessage() {}

func (x *CreateSecretSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{29}
}

func (x *CreateSecretSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSecretSessionResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *CreateSecretSessionResponse) GetSealedTokens() map[string]string {
	if x != nil {
		return x.SealedTokens
	}
	return nil
}

func (x *CreateSecretSessionResponse) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

func (x *CreateSecretSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ResolveSecretSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSecretSessionRequest) Reset() {
	*x = ResolveSecretSessionRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSecretSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSecretSessionRequest) ProtoMessage() {}

func (x *ResolveSecretSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSecretSessionRequest.ProtoReflect.Descriptor instead.
func (*ResolveSecretSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{30}
}

func (x *ResolveSecretSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResolveSecretSessionRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type ResolveSecretSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenValues   map[string]string      `protobuf:"bytes,1,rep,name=token_values,json=tokenValues,proto3" json:"token_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // {"osb_sealed_xxx": "real-api-key"}
	AllowedHosts  []string               `protobuf:"bytes,2,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSecretSessionResponse) Reset() {
	*x = ResolveSecretSessionResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSecretSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSecretSessionResponse) ProtoMessage() {}

func (x *ResolveSecretSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSecretSessionResponse.ProtoReflect.Descriptor instead.
func (*ResolveSecretSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{31}
}

func (x *ResolveSecretSessionResponse) GetTokenValues() map[string]string {
	if x != nil {
		return x.TokenValues
	}
	return nil
}

func (x *ResolveSecretSessionResponse) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

type DeleteSecretSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretSessionRequest) Reset() {
	*x = DeleteSecretSessionRequest{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretSessionRequest) ProtoMessage() {}

func (x *DeleteSecretSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteSecretSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSecretSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretSessionResponse) Reset() {
	*x = DeleteSecretSessionResponse{}
	mi := &file_proto_secrets_secrets_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretSessionResponse) ProtoMessage() {}

func (x *DeleteSecretSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_secrets_secrets_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_secrets_secrets_proto_rawDescGZIP(), []int{33}
}

var File_proto_secrets_secrets_proto protoreflect.FileDescriptor

const file_proto_secrets_secrets_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/secrets/secrets.proto\x12\asecrets\"\xa3\x01\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\"\x8b\x01\n" +
	"\x13CreateSecretRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fplaintext_value\x18\x04 \x01(\tR\x0eplaintextValue\"?\n" +
	"\x14CreateSecretResponse\x12'\n" +
	"\x06secret\x18\x01 \x01(\v2\x0f.secrets.SecretR\x06secret\"+\n" +
	"\x12ListSecretsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"@\n" +
	"\x13ListSecretsResponse\x12)\n" +
	"\asecrets\x18\x01 \x03(\v2\x0f.secrets.SecretR\asecrets\"\xaf\x01\n" +
	"\x13UpdateSecretRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12 \n" +
	"\tnew_value\x18\x05 \x01(\tH\x00R\bnewValue\x88\x01\x01B\f\n" +
	"\n" +
	"_new_value\"\x16\n" +
	"\x14UpdateSecretResponse\"I\n" +
	"\x13DeleteSecretRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\"\x16\n" +
	"\x14DeleteSecretResponse\"\xae\x01\n" +
	"\vSecretGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rallowed_hosts\x18\x05 \x03(\tR\fallowedHosts\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"\x8c\x01\n" +
	"\x18CreateSecretGroupRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rallowed_hosts\x18\x04 \x03(\tR\fallowedHosts\"G\n" +
	"\x19CreateSecretGroupResponse\x12*\n" +
	"\x05group\x18\x01 \x01(\v2\x14.secrets.SecretGroupR\x05group\"0\n" +
	"\x17ListSecretGroupsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"H\n" +
	"\x18ListSecretGroupsResponse\x12,\n" +
	"\x06groups\x18\x01 \x03(\v2\x14.secrets.SecretGroupR\x06groups\"I\n" +
	"\x15GetSecretGroupRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"D\n" +
	"\x16GetSecretGroupResponse\x12*\n" +
	"\x05group\x18\x01 \x01(\v2\x14.secrets.SecretGroupR\x05group\"\xa7\x01\n" +
	"\x18UpdateSecretGroupRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rallowed_hosts\x18\x05 \x03(\tR\fallowedHosts\"\x1b\n" +
	"\x19UpdateSecretGroupResponse\"L\n" +
	"\x18DeleteSecretGroupRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"\x1b\n" +
	"\x19DeleteSecretGroupResponse\"\x9d\x01\n" +
	"\x10SecretGroupEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\tsecret_id\x18\x03 \x01(\tR\bsecretId\x12\x1f\n" +
	"\vsecret_name\x18\x04 \x01(\tR\n" +
	"secretName\x12 \n" +
	"\fenv_var_name\x18\x05 \x01(\tR\n" +
	"envVarName\"s\n" +
	"\x1cSetSecretGroupEntriesRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.secrets.SecretGroupEntryInputR\aentries\"V\n" +
	"\x15SecretGroupEntryInput\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x12 \n" +
	"\fenv_var_name\x18\x02 \x01(\tR\n" +
	"envVarName\"\x1f\n" +
	"\x1dSetSecretGroupEntriesResponse\"9\n" +
	"\x1cGetSecretGroupEntriesRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"T\n" +
	"\x1dGetSecretGroupEntriesResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.secrets.SecretGroupEntryR\aentries\"M\n" +
	"\x19ResolveSecretGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"\xca\x01\n" +
	"\x1aResolveSecretGroupResponse\x12K\n" +
	"\benv_vars\x18\x01 \x03(\v20.secrets.ResolveSecretGroupResponse.EnvVarsEntryR\aenvVars\x12#\n" +
	"\rallowed_hosts\x18\x02 \x03(\tR\fallowedHosts\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x1aCreateSecretSessionRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x03 \x01(\tR\tsandboxId\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x05R\n" +
	"ttlSeconds\"\xc3\x02\n" +
	"\x1bCreateSecretSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12[\n" +
	"\rsealed_tokens\x18\x03 \x03(\v26.secrets.CreateSecretSessionResponse.SealedTokensEntryR\fsealedTokens\x12#\n" +
	"\rallowed_hosts\x18\x04 \x03(\tR\fallowedHosts\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x1a?\n" +
	"\x11SealedTokensEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x1bResolveSecretSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\"\xde\x01\n" +
	"\x1cResolveSecretSessionResponse\x12Y\n" +
	"\ftoken_values\x18\x01 \x03(\v26.secrets.ResolveSecretSessionResponse.TokenValuesEntryR\vtokenValues\x12#\n" +
	"\rallowed_hosts\x18\x02 \x03(\tR\fallowedHosts\x1a>\n" +
	"\x10TokenValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x1aDeleteSecretSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x1d\n" +
	"\x1bDeleteSecretSessionResponse2\xd9\n" +
	"\n" +
	"\x0eSecretsService\x12K\n" +
	"\fCreateSecret\x12\x1c.secrets.CreateSecretRequest\x1a\x1d.secrets.CreateSecretResponse\x12H\n" +
	"\vListSecrets\x12\x1b.secrets.ListSecretsRequest\x1a\x1c.secrets.ListSecretsResponse\x12K\n" +
	"\fUpdateSecret\x12\x1c.secrets.UpdateSecretRequest\x1a\x1d.secrets.UpdateSecretResponse\x12K\n" +
	"\fDeleteSecret\x12\x1c.secrets.DeleteSecretRequest\x1a\x1d.secrets.DeleteSecretResponse\x12Z\n" +
	"\x11CreateSecretGroup\x12!.secrets.CreateSecretGroupRequest\x1a\".secrets.CreateSecretGroupResponse\x12W\n" +
	"\x10ListSecretGroups\x12 .secrets.ListSecretGroupsRequest\x1a!.secrets.ListSecretGroupsResponse\x12Q\n" +
	"\x0eGetSecretGroup\x12\x1e.secrets.GetSecretGroupRequest\x1a\x1f.secrets.GetSecretGroupResponse\x12Z\n" +
	"\x11UpdateSecretGroup\x12!.secrets.UpdateSecretGroupRequest\x1a\".secrets.UpdateSecretGroupResponse\x12Z\n" +
	"\x11DeleteSecretGroup\x12!.secrets.DeleteSecretGroupRequest\x1a\".secrets.DeleteSecretGroupResponse\x12f\n" +
	"\x15SetSecretGroupEntries\x12%.secrets.SetSecretGroupEntriesRequest\x1a&.secrets.SetSecretGroupEntriesResponse\x12f\n" +
	"\x15GetSecretGroupEntries\x12%.secrets.GetSecretGroupEntriesRequest\x1a&.secrets.GetSecretGroupEntriesResponse\x12]\n" +
	"\x12ResolveSecretGroup\x12\".secrets.ResolveSecretGroupRequest\x1a#.secrets.ResolveSecretGroupResponse\x12`\n" +
	"\x13CreateSecretSession\x12#.secrets.CreateSecretSessionRequest\x1a$.secrets.CreateSecretSessionResponse\x12c\n" +
	"\x14ResolveSecretSession\x12$.secrets.ResolveSecretSessionRequest\x1a%.secrets.ResolveSecretSessionResponse\x12`\n" +
	"\x13DeleteSecretSession\x12#.secrets.DeleteSecretSessionRequest\x1a$.secrets.DeleteSecretSessionResponseB2Z0github.com/opensandbox/opensandbox/proto/secretsb\x06proto3"

var (
	file_proto_secrets_secrets_proto_rawDescOnce sync.Once
	file_proto_secrets_secrets_proto_rawDescData []byte
)

func file_proto_secrets_secrets_proto_rawDescGZIP() []byte {
	file_proto_secrets_secrets_proto_rawDescOnce.Do(func() {
		file_proto_secrets_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_secrets_secrets_proto_rawDesc), len(file_proto_secrets_secrets_proto_rawDesc)))
	})
	return file_proto_secrets_secrets_proto_rawDescData
}

var file_proto_secrets_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_secrets_secrets_proto_goTypes = []any{
	(*Secret)(nil),                        // 0: secrets.Secret
	(*CreateSecretRequest)(nil),           // 1: secrets.CreateSecretRequest
	(*CreateSecretResponse)(nil),          // 2: secrets.CreateSecretResponse
	(*ListSecretsRequest)(nil),            // 3: secrets.ListSecretsRequest
	(*ListSecretsResponse)(nil),           // 4: secrets.ListSecretsResponse
	(*UpdateSecretRequest)(nil),           // 5: secrets.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),          // 6: secrets.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),           // 7: secrets.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),          // 8: secrets.DeleteSecretResponse
	(*SecretGroup)(nil),                   // 9: secrets.SecretGroup
	(*CreateSecretGroupRequest)(nil),      // 10: secrets.CreateSecretGroupRequest
	(*CreateSecretGroupResponse)(nil),     // 11: secrets.CreateSecretGroupResponse
	(*ListSecretGroupsRequest)(nil),       // 12: secrets.ListSecretGroupsRequest
	(*ListSecretGroupsResponse)(nil),      // 13: secrets.ListSecretGroupsResponse
	(*GetSecretGroupRequest)(nil),         // 14: secrets.GetSecretGroupRequest
	(*GetSecretGroupResponse)(nil),        // 15: secrets.GetSecretGroupResponse
	(*UpdateSecretGroupRequest)(nil),      // 16: secrets.UpdateSecretGroupRequest
	(*UpdateSecretGroupResponse)(nil),     // 17: secrets.UpdateSecretGroupResponse
	(*DeleteSecretGroupRequest)(nil),      // 18: secrets.DeleteSecretGroupRequest
	(*DeleteSecretGroupResponse)(nil),     // 19: secrets.DeleteSecretGroupResponse
	(*SecretGroupEntry)(nil),              // 20: secrets.SecretGroupEntry
	(*SetSecretGroupEntriesRequest)(nil),  // 21: secrets.SetSecretGroupEntriesRequest
	(*SecretGroupEntryInput)(nil),         // 22: secrets.SecretGroupEntryInput
	(*SetSecretGroupEntriesResponse)(nil), // 23: secrets.SetSecretGroupEntriesResponse
	(*GetSecretGroupEntriesRequest)(nil),  // 24: secrets.GetSecretGroupEntriesRequest
	(*GetSecretGroupEntriesResponse)(nil), // 25: secrets.GetSecretGroupEntriesResponse
	(*ResolveSecretGroupRequest)(nil),     // 26: secrets.ResolveSecretGroupRequest
	(*ResolveSecretGroupResponse)(nil),    // 27: secrets.ResolveSecretGroupResponse
	(*CreateSecretSessionRequest)(nil),    // 28: secrets.CreateSecretSessionRequest
	(*CreateSecretSessionResponse)(nil),   // 29: secrets.CreateSecretSessionResponse
	(*ResolveSecretSessionRequest)(nil),   // 30: secrets.ResolveSecretSessionRequest
	(*ResolveSecretSessionResponse)(nil),  // 31: secrets.ResolveSecretSessionResponse
	(*DeleteSecretSessionRequest)(nil),    // 32: secrets.DeleteSecretSessionRequest
	(*DeleteSecretSessionResponse)(nil),   // 33: secrets.DeleteSecretSessionResponse
	nil,                                   // 34: secrets.ResolveSecretGroupResponse.EnvVarsEntry
	nil,                                   // 35: secrets.CreateSecretSessionResponse.SealedTokensEntry
	nil,                                   // 36: secrets.ResolveSecretSessionResponse.TokenValuesEntry
}
var file_proto_secrets_secrets_proto_depIdxs = []int32{
	0,  // 0: secrets.CreateSecretResponse.secret:type_name -> secrets.Secret
	0,  // 1: secrets.ListSecretsResponse.secrets:type_name -> secrets.Secret
	9,  // 2: secrets.CreateSecretGroupResponse.group:type_name -> secrets.SecretGroup
	9,  // 3: secrets.ListSecretGroupsResponse.groups:type_name -> secrets.SecretGroup
	9,  // 4: secrets.GetSecretGroupResponse.group:type_name -> secrets.SecretGroup
	22, // 5: secrets.SetSecretGroupEntriesRequest.entries:type_name -> secrets.SecretGroupEntryInput
	20, // 6: secrets.GetSecretGroupEntriesResponse.entries:type_name -> secrets.SecretGroupEntry
	34, // 7: secrets.ResolveSecretGroupResponse.env_vars:type_name -> secrets.ResolveSecretGroupResponse.EnvVarsEntry
	35, // 8: secrets.CreateSecretSessionResponse.sealed_tokens:type_name -> secrets.CreateSecretSessionResponse.SealedTokensEntry
	36, // 9: secrets.ResolveSecretSessionResponse.token_values:type_name -> secrets.ResolveSecretSessionResponse.TokenValuesEntry
	1,  // 10: secrets.SecretsService.CreateSecret:input_type -> secrets.CreateSecretRequest
	3,  // 11: secrets.SecretsService.ListSecrets:input_type -> secrets.ListSecretsRequest
	5,  // 12: secrets.SecretsService.UpdateSecret:input_type -> secrets.UpdateSecretRequest
	7,  // 13: secrets.SecretsService.DeleteSecret:input_type -> secrets.DeleteSecretRequest
	10, // 14: secrets.SecretsService.CreateSecretGroup:input_type -> secrets.CreateSecretGroupRequest
	12, // 15: secrets.SecretsService.ListSecretGroups:input_type -> secrets.ListSecretGroupsRequest
	14, // 16: secrets.SecretsService.GetSecretGroup:input_type -> secrets.GetSecretGroupRequest
	16, // 17: secrets.SecretsService.UpdateSecretGroup:input_type -> secrets.UpdateSecretGroupRequest
	18, // 18: secrets.SecretsService.DeleteSecretGroup:input_type -> secrets.DeleteSecretGroupRequest
	21, // 19: secrets.SecretsService.SetSecretGroupEntries:input_type -> secrets.SetSecretGroupEntriesRequest
	24, // 20: secrets.SecretsService.GetSecretGroupEntries:input_type -> secrets.GetSecretGroupEntriesRequest
	26, // 21: secrets.SecretsService.ResolveSecretGroup:input_type -> secrets.ResolveSecretGroupRequest
	28, // 22: secrets.SecretsService.CreateSecretSession:input_type -> secrets.CreateSecretSessionRequest
	30, // 23: secrets.SecretsService.ResolveSecretSession:input_type -> secrets.ResolveSecretSessionRequest
	32, // 24: secrets.SecretsService.DeleteSecretSession:input_type -> secrets.DeleteSecretSessionRequest
	2,  // 25: secrets.SecretsService.CreateSecret:output_type -> secrets.CreateSecretResponse
	4,  // 26: secrets.SecretsService.ListSecrets:output_type -> secrets.ListSecretsResponse
	6,  // 27: secrets.SecretsService.UpdateSecret:output_type -> secrets.UpdateSecretResponse
	8,  // 28: secrets.SecretsService.DeleteSecret:output_type -> secrets.DeleteSecretResponse
	11, // 29: secrets.SecretsService.CreateSecretGroup:output_type -> secrets.CreateSecretGroupResponse
	13, // 30: secrets.SecretsService.ListSecretGroups:output_type -> secrets.ListSecretGroupsResponse
	15, // 31: secrets.SecretsService.GetSecretGroup:output_type -> secrets.GetSecretGroupResponse
	17, // 32: secrets.SecretsService.UpdateSecretGroup:output_type -> secrets.UpdateSecretGroupResponse
	19, // 33: secrets.SecretsService.DeleteSecretGroup:output_type -> secrets.DeleteSecretGroupResponse
	23, // 34: secrets.SecretsService.SetSecretGroupEntries:output_type -> secrets.SetSecretGroupEntriesResponse
	25, // 35: secrets.SecretsService.GetSecretGroupEntries:output_type -> secrets.GetSecretGroupEntriesResponse
	27, // 36: secrets.SecretsService.ResolveSecretGroup:output_type -> secrets.ResolveSecretGroupResponse
	29, // 37: secrets.SecretsService.CreateSecretSession:output_type -> secrets.CreateSecretSessionResponse
	31, // 38: secrets.SecretsService.ResolveSecretSession:output_type -> secrets.ResolveSecretSessionResponse
	33, // 39: secrets.SecretsService.DeleteSecretSession:output_type -> secrets.DeleteSecretSessionResponse
	25, // [25:40] is the sub-list for method output_type
	10, // [10:25] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_secrets_secrets_proto_init() }
func file_proto_secrets_secrets_proto_init() {
	if File_proto_secrets_secrets_proto != nil {
		return
	}
	file_proto_secrets_secrets_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_secrets_secrets_proto_rawDesc), len(file_proto_secrets_secrets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_secrets_secrets_proto_goTypes,
		DependencyIndexes: file_proto_secrets_secrets_proto_depIdxs,
		MessageInfos:      file_proto_secrets_secrets_proto_msgTypes,
	}.Build()
	File_proto_secrets_secrets_proto = out.File
	file_proto_secrets_secrets_proto_goTypes = nil
	file_proto_secrets_secrets_proto_depIdxs = nil
}
