// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/secrets/secrets.proto

package secrets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretsService_CreateSecret_FullMethodName          = "/secrets.SecretsService/CreateSecret"
	SecretsService_ListSecrets_FullMethodName           = "/secrets.SecretsService/ListSecrets"
	SecretsService_UpdateSecret_FullMethodName          = "/secrets.SecretsService/UpdateSecret"
	SecretsService_DeleteSecret_FullMethodName          = "/secrets.SecretsService/DeleteSecret"
	SecretsService_CreateSecretGroup_FullMethodName     = "/secrets.SecretsService/CreateSecretGroup"
	SecretsService_ListSecretGroups_FullMethodName      = "/secrets.SecretsService/ListSecretGroups"
	SecretsService_GetSecretGroup_FullMethodName        = "/secrets.SecretsService/GetSecretGroup"
	SecretsService_UpdateSecretGroup_FullMethodName     = "/secrets.SecretsService/UpdateSecretGroup"
	SecretsService_DeleteSecretGroup_FullMethodName     = "/secrets.SecretsService/DeleteSecretGroup"
	SecretsService_SetSecretGroupEntries_FullMethodName = "/secrets.SecretsService/SetSecretGroupEntries"
	SecretsService_GetSecretGroupEntries_FullMethodName = "/secrets.SecretsService/GetSecretGroupEntries"
	SecretsService_ResolveSecretGroup_FullMethodName    = "/secrets.SecretsService/ResolveSecretGroup"
	SecretsService_CreateSecretSession_FullMethodName   = "/secrets.SecretsService/CreateSecretSession"
	SecretsService_ResolveSecretSession_FullMethodName  = "/secrets.SecretsService/ResolveSecretSession"
	SecretsService_DeleteSecretSession_FullMethodName   = "/secrets.SecretsService/DeleteSecretSession"
)

// SecretsServiceClient is the client API for SecretsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecretsServiceClient interface {
	// Secret CRUD
	CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error)
	ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error)
	UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error)
	DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error)
	// Secret Group CRUD
	CreateSecretGroup(ctx context.Context, in *CreateSecretGroupRequest, opts ...grpc.CallOption) (*CreateSecretGroupResponse, error)
	ListSecretGroups(ctx context.Context, in *ListSecretGroupsRequest, opts ...grpc.CallOption) (*ListSecretGroupsResponse, error)
	GetSecretGroup(ctx context.Context, in *GetSecretGroupRequest, opts ...grpc.CallOption) (*GetSecretGroupResponse, error)
	UpdateSecretGroup(ctx context.Context, in *UpdateSecretGroupRequest, opts ...grpc.CallOption) (*UpdateSecretGroupResponse, error)
	DeleteSecretGroup(ctx context.Context, in *DeleteSecretGroupRequest, opts ...grpc.CallOption) (*DeleteSecretGroupResponse, error)
	// Secret Group Entries
	SetSecretGroupEntries(ctx context.Context, in *SetSecretGroupEntriesRequest, opts ...grpc.CallOption) (*SetSecretGroupEntriesResponse, error)
	GetSecretGroupEntries(ctx context.Context, in *GetSecretGroupEntriesRequest, opts ...grpc.CallOption) (*GetSecretGroupEntriesResponse, error)
	// Hot path: resolve a group into plaintext env vars + allowed hosts
	ResolveSecretGroup(ctx context.Context, in *ResolveSecretGroupRequest, opts ...grpc.CallOption) (*ResolveSecretGroupResponse, error)
	// Session-based secret access — control plane never sees plaintext.
	// CreateSecretSession resolves + stores secrets server-side, returns sealed tokens.
	// ResolveSecretSession gives the worker the {sealedToken → realValue} mapping.
	CreateSecretSession(ctx context.Context, in *CreateSecretSessionRequest, opts ...grpc.CallOption) (*CreateSecretSessionResponse, error)
	ResolveSecretSession(ctx context.Context, in *ResolveSecretSessionRequest, opts ...grpc.CallOption) (*ResolveSecretSessionResponse, error)
	DeleteSecretSession(ctx context.Context, in *DeleteSecretSessionRequest, opts ...grpc.CallOption) (*DeleteSecretSessionResponse, error)
}

type secretsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsServiceClient(cc grpc.ClientConnInterface) SecretsServiceClient {
	return &secretsServiceClient{cc}
}

func (c *secretsServiceClient) CreateSecret(ctx context.Context, in *CreateSecretRequest, opts ...grpc.CallOption) (*CreateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ListSecrets(ctx context.Context, in *ListSecretsRequest, opts ...grpc.CallOption) (*ListSecretsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretsResponse)
	err := c.cc.Invoke(ctx, SecretsService_ListSecrets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) UpdateSecret(ctx context.Context, in *UpdateSecretRequest, opts ...grpc.CallOption) (*UpdateSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_UpdateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) DeleteSecret(ctx context.Context, in *DeleteSecretRequest, opts ...grpc.CallOption) (*DeleteSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretResponse)
	err := c.cc.Invoke(ctx, SecretsService_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) CreateSecretGroup(ctx context.Context, in *CreateSecretGroupRequest, opts ...grpc.CallOption) (*CreateSecretGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretGroupResponse)
	err := c.cc.Invoke(ctx, SecretsService_CreateSecretGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ListSecretGroups(ctx context.Context, in *ListSecretGroupsRequest, opts ...grpc.CallOption) (*ListSecretGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSecretGroupsResponse)
	err := c.cc.Invoke(ctx, SecretsService_ListSecretGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) GetSecretGroup(ctx context.Context, in *GetSecretGroupRequest, opts ...grpc.CallOption) (*GetSecretGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretGroupResponse)
	err := c.cc.Invoke(ctx, SecretsService_GetSecretGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) UpdateSecretGroup(ctx context.Context, in *UpdateSecretGroupRequest, opts ...grpc.CallOption) (*UpdateSecretGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSecretGroupResponse)
	err := c.cc.Invoke(ctx, SecretsService_UpdateSecretGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) DeleteSecretGroup(ctx context.Context, in *DeleteSecretGroupRequest, opts ...grpc.CallOption) (*DeleteSecretGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretGroupResponse)
	err := c.cc.Invoke(ctx, SecretsService_DeleteSecretGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) SetSecretGroupEntries(ctx context.Context, in *SetSecretGroupEntriesRequest, opts ...grpc.CallOption) (*SetSecretGroupEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecretGroupEntriesResponse)
	err := c.cc.Invoke(ctx, SecretsService_SetSecretGroupEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) GetSecretGroupEntries(ctx context.Context, in *GetSecretGroupEntriesRequest, opts ...grpc.CallOption) (*GetSecretGroupEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretGroupEntriesResponse)
	err := c.cc.Invoke(ctx, SecretsService_GetSecretGroupEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ResolveSecretGroup(ctx context.Context, in *ResolveSecretGroupRequest, opts ...grpc.CallOption) (*ResolveSecretGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretGroupResponse)
	err := c.cc.Invoke(ctx, SecretsService_ResolveSecretGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) CreateSecretSession(ctx context.Context, in *CreateSecretSessionRequest, opts ...grpc.CallOption) (*CreateSecretSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSecretSessionResponse)
	err := c.cc.Invoke(ctx, SecretsService_CreateSecretSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) ResolveSecretSession(ctx context.Context, in *ResolveSecretSessionRequest, opts ...grpc.CallOption) (*ResolveSecretSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretSessionResponse)
	err := c.cc.Invoke(ctx, SecretsService_ResolveSecretSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretsServiceClient) DeleteSecretSession(ctx context.Context, in *DeleteSecretSessionRequest, opts ...grpc.CallOption) (*DeleteSecretSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSecretSessionResponse)
	err := c.cc.Invoke(ctx, SecretsService_DeleteSecretSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsServiceServer is the server API for SecretsService service.
// All implementations must embed UnimplementedSecretsServiceServer
// for forward compatibility.
type SecretsServiceServer interface {
	// Secret CRUD
	CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error)
	ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error)
	UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error)
	DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error)
	// Secret Group CRUD
	CreateSecretGroup(context.Context, *CreateSecretGroupRequest) (*CreateSecretGroupResponse, error)
	ListSecretGroups(context.Context, *ListSecretGroupsRequest) (*ListSecretGroupsResponse, error)
	GetSecretGroup(context.Context, *GetSecretGroupRequest) (*GetSecretGroupResponse, error)
	UpdateSecretGroup(context.Context, *UpdateSecretGroupRequest) (*UpdateSecretGroupResponse, error)
	DeleteSecretGroup(context.Context, *DeleteSecretGroupRequest) (*DeleteSecretGroupResponse, error)
	// Secret Group Entries
	SetSecretGroupEntries(context.Context, *SetSecretGroupEntriesRequest) (*SetSecretGroupEntriesResponse, error)
	GetSecretGroupEntries(context.Context, *GetSecretGroupEntriesRequest) (*GetSecretGroupEntriesResponse, error)
	// Hot path: resolve a group into plaintext env vars + allowed hosts
	ResolveSecretGroup(context.Context, *ResolveSecretGroupRequest) (*ResolveSecretGroupResponse, error)
	// Session-based secret access — control plane never sees plaintext.
	// CreateSecretSession resolves + stores secrets server-side, returns sealed tokens.
	// ResolveSecretSession gives the worker the {sealedToken → realValue} mapping.
	CreateSecretSession(context.Context, *CreateSecretSessionRequest) (*CreateSecretSessionResponse, error)
	ResolveSecretSession(context.Context, *ResolveSecretSessionRequest) (*ResolveSecretSessionResponse, error)
	DeleteSecretSession(context.Context, *DeleteSecretSessionRequest) (*DeleteSecretSessionResponse, error)
	mustEmbedUnimplementedSecretsServiceServer()
}

// UnimplementedSecretsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsServiceServer struct{}

func (UnimplementedSecretsServiceServer) CreateSecret(context.Context, *CreateSecretRequest) (*CreateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedSecretsServiceServer) ListSecrets(context.Context, *ListSecretsRequest) (*ListSecretsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecrets not implemented")
}
func (UnimplementedSecretsServiceServer) UpdateSecret(context.Context, *UpdateSecretRequest) (*UpdateSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecret not implemented")
}
func (UnimplementedSecretsServiceServer) DeleteSecret(context.Context, *DeleteSecretRequest) (*DeleteSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedSecretsServiceServer) CreateSecretGroup(context.Context, *CreateSecretGroupRequest) (*CreateSecretGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecretGroup not implemented")
}
func (UnimplementedSecretsServiceServer) ListSecretGroups(context.Context, *ListSecretGroupsRequest) (*ListSecretGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSecretGroups not implemented")
}
func (UnimplementedSecretsServiceServer) GetSecretGroup(context.Context, *GetSecretGroupRequest) (*GetSecretGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecretGroup not implemented")
}
func (UnimplementedSecretsServiceServer) UpdateSecretGroup(context.Context, *UpdateSecretGroupRequest) (*UpdateSecretGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecretGroup not implemented")
}
func (UnimplementedSecretsServiceServer) DeleteSecretGroup(context.Context, *DeleteSecretGroupRequest) (*DeleteSecretGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecretGroup not implemented")
}
func (UnimplementedSecretsServiceServer) SetSecretGroupEntries(context.Context, *SetSecretGroupEntriesRequest) (*SetSecretGroupEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSecretGroupEntries not implemented")
}
func (UnimplementedSecretsServiceServer) GetSecretGroupEntries(context.Context, *GetSecretGroupEntriesRequest) (*GetSecretGroupEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecretGroupEntries not implemented")
}
func (UnimplementedSecretsServiceServer) ResolveSecretGroup(context.Context, *ResolveSecretGroupRequest) (*ResolveSecretGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSecretGroup not implemented")
}
func (UnimplementedSecretsServiceServer) CreateSecretSession(context.Context, *CreateSecretSessionRequest) (*CreateSecretSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSecretSession not implemented")
}
func (UnimplementedSecretsServiceServer) ResolveSecretSession(context.Context, *ResolveSecretSessionRequest) (*ResolveSecretSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSecretSession not implemented")
}
func (UnimplementedSecretsServiceServer) DeleteSecretSession(context.Context, *DeleteSecretSessionRequest) (*DeleteSecretSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSecretSession not implemented")
}
func (UnimplementedSecretsServiceServer) mustEmbedUnimplementedSecretsServiceServer() {}
func (UnimplementedSecretsServiceServer) testEmbeddedByValue()                        {}

// UnsafeSecretsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsServiceServer will
// result in compilation errors.
type UnsafeSecretsServiceServer interface {
	mustEmbedUnimplementedSecretsServiceServer()
}

func RegisterSecretsServiceServer(s grpc.ServiceRegistrar, srv SecretsServiceServer) {
	// If the following call panics, it indicates UnimplementedSecretsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretsService_ServiceDesc, srv)
}

func _SecretsService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).CreateSecret(ctx, req.(*CreateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ListSecrets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ListSecrets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ListSecrets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ListSecrets(ctx, req.(*ListSecretsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_UpdateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).UpdateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_UpdateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).UpdateSecret(ctx, req.(*UpdateSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).DeleteSecret(ctx, req.(*DeleteSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_CreateSecretGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).CreateSecretGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_CreateSecretGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).CreateSecretGroup(ctx, req.(*CreateSecretGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ListSecretGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ListSecretGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ListSecretGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ListSecretGroups(ctx, req.(*ListSecretGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_GetSecretGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).GetSecretGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_GetSecretGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).GetSecretGroup(ctx, req.(*GetSecretGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_UpdateSecretGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).UpdateSecretGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_UpdateSecretGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).UpdateSecretGroup(ctx, req.(*UpdateSecretGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_DeleteSecretGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).DeleteSecretGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_DeleteSecretGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).DeleteSecretGroup(ctx, req.(*DeleteSecretGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_SetSecretGroupEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecretGroupEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).SetSecretGroupEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_SetSecretGroupEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).SetSecretGroupEntries(ctx, req.(*SetSecretGroupEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_GetSecretGroupEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretGroupEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).GetSecretGroupEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_GetSecretGroupEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).GetSecretGroupEntries(ctx, req.(*GetSecretGroupEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ResolveSecretGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSecretGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ResolveSecretGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ResolveSecretGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ResolveSecretGroup(ctx, req.(*ResolveSecretGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_CreateSecretSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSecretSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).CreateSecretSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_CreateSecretSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).CreateSecretSession(ctx, req.(*CreateSecretSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_ResolveSecretSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSecretSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).ResolveSecretSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_ResolveSecretSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).ResolveSecretSession(ctx, req.(*ResolveSecretSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretsService_DeleteSecretSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSecretSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsServiceServer).DeleteSecretSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsService_DeleteSecretSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsServiceServer).DeleteSecretSession(ctx, req.(*DeleteSecretSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsService_ServiceDesc is the grpc.ServiceDesc for SecretsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secrets.SecretsService",
	HandlerType: (*SecretsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSecret",
			Handler:    _SecretsService_CreateSecret_Handler,
		},
		{
			MethodName: "ListSecrets",
			Handler:    _SecretsService_ListSecrets_Handler,
		},
		{
			MethodName: "UpdateSecret",
			Handler:    _SecretsService_UpdateSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _SecretsService_DeleteSecret_Handler,
		},
		{
			MethodName: "CreateSecretGroup",
			Handler:    _SecretsService_CreateSecretGroup_Handler,
		},
		{
			MethodName: "ListSecretGroups",
			Handler:    _SecretsService_ListSecretGroups_Handler,
		},
		{
			MethodName: "GetSecretGroup",
			Handler:    _SecretsService_GetSecretGroup_Handler,
		},
		{
			MethodName: "UpdateSecretGroup",
			Handler:    _SecretsService_UpdateSecretGroup_Handler,
		},
		{
			MethodName: "DeleteSecretGroup",
			Handler:    _SecretsService_DeleteSecretGroup_Handler,
		},
		{
			MethodName: "SetSecretGroupEntries",
			Handler:    _SecretsService_SetSecretGroupEntries_Handler,
		},
		{
			MethodName: "GetSecretGroupEntries",
			Handler:    _SecretsService_GetSecretGroupEntries_Handler,
		},
		{
			MethodName: "ResolveSecretGroup",
			Handler:    _SecretsService_ResolveSecretGroup_Handler,
		},
		{
			MethodName: "CreateSecretSession",
			Handler:    _SecretsService_CreateSecretSession_Handler,
		},
		{
			MethodName: "ResolveSecretSession",
			Handler:    _SecretsService_ResolveSecretSession_Handler,
		},
		{
			MethodName: "DeleteSecretSession",
			Handler:    _SecretsService_DeleteSecretSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/secrets/secrets.proto",
}
