#!/usr/bin/env node
// Deploy the ChatGPT app Worker into an isolated devin-* preview stack, wired to that stack's
// api-edge over a service binding.
//
//   node scripts/stack.mjs <devin-name> up|destroy
//
// Reads $OC_STACK_HOME/<name>/stack.json (written by api-edge's stack script) and records
// chatgptAppUrl in it. Only `opencomputer-chatgpt-app-devin-*` Workers and KV namespaces are touched.
// Env: CLOUDFLARE_API_TOKEN (falls back to CLOUDFLARE_DEVIN_API_TOKEN).

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ACCOUNT_ID = "10a2123d1440c5fbf090968ca59bfb28";
const [, , name, command] = process.argv;
if (!name || !/^devin-[a-z0-9-]{1,30}$/.test(name) || !["up", "destroy"].includes(command ?? "")) {
  console.error("usage: node scripts/stack.mjs <devin-name> up|destroy");
  process.exit(2);
}
const worker = `opencomputer-chatgpt-app-${name}`;
const stackFile = path.join(process.env.OC_STACK_HOME ?? path.join(os.homedir(), ".oc-stacks"), name, "stack.json");
const configFile = path.join(root, `wrangler.${name}.generated.toml`);
const env = {
  ...process.env,
  CLOUDFLARE_API_TOKEN: process.env.CLOUDFLARE_API_TOKEN ?? process.env.CLOUDFLARE_DEVIN_API_TOKEN,
  CLOUDFLARE_ACCOUNT_ID: ACCOUNT_ID,
};

function wrangler(args, { capture = false } = {}) {
  const result = spawnSync("npx", ["wrangler", ...args], { cwd: root, env, encoding: "utf8", stdio: capture ? "pipe" : "inherit" });
  if (result.status !== 0) {
    if (capture) process.stderr.write(result.stderr ?? "");
    throw new Error(`wrangler ${args[0]} failed`);
  }
  return result.stdout ?? "";
}

const stack = JSON.parse(fs.readFileSync(stackFile, "utf8"));
if (!stack.apiEdgeUrl || !stack.apiEdgeWorker) throw new Error(`${stackFile} has no api-edge; run api-edge's stack script first`);

if (command === "destroy") {
  try { wrangler(["delete", "--name", worker, "--force"]); } catch {}
  if (stack.chatgptApp?.kvId) {
    try { wrangler(["kv", "namespace", "delete", "--namespace-id", stack.chatgptApp.kvId, "--force"]); } catch {}
  }
  delete stack.chatgptApp;
  fs.writeFileSync(stackFile, JSON.stringify(stack, null, 2));
  process.exit(0);
}

let kvId = stack.chatgptApp?.kvId;
if (!kvId) {
  const listed = JSON.parse(wrangler(["kv", "namespace", "list"], { capture: true }));
  kvId = listed.find((ns) => ns.title === worker)?.id;
  if (!kvId) {
    const out = wrangler(["kv", "namespace", "create", worker], { capture: true });
    kvId = /id = "([0-9a-f]{32})"/.exec(out)?.[1] ?? /"id": "([0-9a-f]{32})"/.exec(out)?.[1];
    if (!kvId) throw new Error("could not read the created KV namespace id");
  }
}
const publicUrl = `https://${worker}.${stack.workersDevSubdomain}.workers.dev`;
fs.writeFileSync(
  configFile,
  `# Generated by scripts/stack.mjs for ${name}; not source.
name = "${worker}"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true

[vars]
PUBLIC_URL = "${publicUrl}"
OPENCOMPUTER_API_URL = "${stack.apiEdgeUrl}"
ALLOW_API_KEY_CONNECT = "true"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "${kvId}"

[[services]]
binding = "API_EDGE"
service = "${stack.apiEdgeWorker}"
`,
);
wrangler(["deploy", "--config", configFile]);
stack.chatgptApp = { worker, kvId, url: publicUrl, deployedAt: new Date().toISOString() };
stack.chatgptAppUrl = publicUrl;
fs.writeFileSync(stackFile, JSON.stringify(stack, null, 2));
console.log(JSON.stringify({ chatgptAppUrl: publicUrl, mcpUrl: `${publicUrl}/mcp` }));
